// Every user-facing string on the PUBLIC surface (landing, /om, the
// volunteer form, verify, and the auth pages) lives here, in Norwegian and
// English. The admin UI is deliberately not localized yet — Norwegian orgs
// administer it — but new public-surface text belongs in this file, both
// languages, or it ships Norwegian-only by accident.
//
// Language selection is URL-based (?lang=en) so it works identically in
// server and client components and survives link sharing. Norwegian is the
// default for any other value.

export type Lang = 'no' | 'en';

const no = {
    common: {
        cancel: 'Avbryt',
        loading: 'Laster …',
    },
    landing: {
        tagline: 'Digitalt verifiserbare attester for frivillige – uten at personopplysninger lagres.',
        steps: [
            { title: '1. Fyll ut skjema', text: 'Den frivillige fyller ut organisasjonens skjema med navn, verv og tidsperiode.' },
            { title: '2. Attesten utstedes', text: 'Organisasjonen kontrollerer innholdet og genererer en PDF med QR-kode. Deretter sletter organisasjonen innsendingen din – kun en kryptografisk hash blir igjen.' },
            { title: '3. Hvem som helst kan verifisere', text: 'QR-koden peker til en verifiseringsside som bekrefter at attesten er ekte og uendret.' },
        ],
        privacyTitle: 'Personvern er hele poenget',
        privacyBody: 'Innsendingen din lagres bare frem til organisasjonen har utstedt attesten og slettet den. Av selve attesten lagres aldri navn, verv eller datoer – kun en kryptografisk hash av innholdet. Lekker databasen, lekker ingen utstedte attester. Bare den som har attesten (eller QR-koden på den) vet hva som ble attestert.',
        aboutLink: 'Les mer om hvordan attester.no fungerer og hva som lagres',
        orgsTitle: 'Deltakende organisasjoner',
        orgsSubtitle: 'Skal du be om en attest? Gå til skjemaet til organisasjonen din:',
        adminLogin: 'Logg inn som administrator',
        contactPrompt: 'Vil organisasjonen din ta i bruk attester.no?',
        contactLink: 'Ta kontakt på GitHub',
    },
    about: {
        metaTitle: 'Slik fungerer det',
        title: 'Slik fungerer attester.no',
        intro: 'attester.no beviser at en attest er ekte – uten at det som står i den lagres permanent. Denne siden forklarer nøyaktig hva som skjer med opplysningene dine.',
        flowTitle: 'Hva skjer med innsendingen din?',
        flowSteps: [
            'Du fyller ut skjemaet til organisasjonen din. Opplysningene lagres inntil organisasjonen har kontrollert dem og utstedt attesten.',
            'Når organisasjonen godkjenner, lages attesten som PDF med en QR-kode, og du får den fra organisasjonen.',
            'Etter utstedelse sletter organisasjonen opplysningene dine fra databasen – da er kun den kryptografiske hashen igjen.',
            'Hører du ikke noe, kan du når som helst kontakte organisasjonen og be dem slette innsendingen din.',
        ],
        storedTitle: 'Hva lagres – og hva lagres aldri?',
        storedIntro: 'Når attesten er utstedt og innsendingen slettet, inneholder databasen kun:',
        storedItems: [
            'En kryptografisk hash (et «fingeravtrykk») av attestens innhold',
            'Hvilken organisasjon som utstedte den, og når',
            'Hvilken PDF-mal som ble brukt',
            'En tilfeldig ID som QR-koden slår opp på',
        ],
        neverStoredIntro: 'Dette lagres ALDRI som en del av attesten:',
        neverStoredItems: [
            'Navnet ditt',
            'Verv, roller eller grupper',
            'Datoer og tidsperioder',
            'Alt annet som står i attesten',
        ],
        hashTitle: 'Hvordan kan attesten verifiseres uten at innholdet er lagret?',
        hashBody: 'QR-koden på attesten inneholder opplysningene – ikke databasen. Når noen skanner koden, regner verifiseringssiden ut fingeravtrykket av opplysningene i koden og sammenligner med fingeravtrykket vi lagret da attesten ble utstedt. Stemmer de, er attesten ekte og uendret. Endres så mye som ett tegn, stemmer de ikke lenger.',
        hashConsequence: 'Konsekvensen: skulle databasen lekke, lekker ingen personopplysninger fra utstedte attester. Serveren vet ikke engang hvem attestene handler om. Bare den som har attesten på papir – eller QR-koden – kan lese innholdet.',
        verifyTitle: 'Slik verifiserer du en attest',
        verifySteps: [
            'Skann QR-koden på attesten med mobilkameraet.',
            'Verifiseringssiden åpnes og viser grønt hvis attesten er ekte og uendret, rødt hvis noe ikke stemmer.',
            'Sammenlign feltene på siden med det som står på papiret.',
        ],
        contactTitle: 'Spørsmål?',
        contactBody: 'Send e-post til hei@attester.no, eller ta kontakt på GitHub.',
        backToFront: 'Til forsiden',
    },
    form: {
        title: (org: string) => `Søk om attest til ${org}`,
        intro: (org: string) => `Her kan du sende inn din informasjon for å få en attest fra ${org}!`,
        help: 'Hjelp',
        adminLogin: 'Admin innlogging',
        noTemplate: (id: string | null) => `Ingen mal funnet for denne organisasjonen${id ? ` (id ${id})` : ''}.`,
        submit: 'Send inn',
        confirmTitle: 'Bekreft innsending',
        confirmMessage: 'Er du sikker på at du vil lagre disse dataene?',
        confirmButton: 'Ja, lagre',
        submitError: 'Feil ved lagring av data: ',
        receivedTitle: 'Innsendingen er mottatt',
        receivedWhatNext: 'Dette skjer videre:',
        receivedSteps: (org: string) => [
            `${org} kontrollerer opplysningene dine. Frem til det skjer, lagres innsendingen din hos attester.no.`,
            `Godkjennes de, lages attesten som PDF med QR-kode, og du får den fra ${org}.`,
            `Når attesten er utstedt, sletter ${org} opplysningene dine fra databasen — bare en kryptografisk hash blir igjen, så attesten kan verifiseres.`,
            `Hører du ikke noe, kan du kontakte ${org} og be dem slette innsendingen din.`,
        ],
        sendAnother: 'Send inn en ny',
        helpTitle: 'Hva er denne nettsiden?',
        helpBody: (org: string) => `Dette er en nettside for å gi deg attest fra ${org}. Du sender inn din informasjon, en administrator kontrollerer den, og godkjennes den får du en PDF med QR-kode — deretter sletter ${org} informasjonen din fra databasen. Kun en hash lagres permanent, slik at attesten kan verifiseres.`,
        helpMore: 'Les mer om hvordan det fungerer og hva som lagres',
        helpClose: 'Takk for info 😊',
    },
    verify: {
        title: 'Verifikasjon',
        checking: 'Kontrollerer attesten …',
        validTitle: '✓ Attesten er gyldig',
        validBody: 'Opplysningene under stemmer nøyaktig med attesten slik den ble utstedt. Endres så mye som ett tegn, blir den ugyldig.',
        invalidTitle: '✗ Attesten er ugyldig',
        invalidBody: 'Opplysningene stemmer ikke med noen utstedt attest. Enten er lenken ufullstendig (skann QR-koden på nytt), et felt er endret, eller attesten er aldri utstedt av denne organisasjonen.',
        fieldsLabel: 'Attesterte opplysninger — du kan endre et felt for å se at verifiseringen da slår feil:',
        aboutLink: 'Hvordan fungerer dette?',
    },
    auth: {
        loginTitle: 'Logg inn',
        email: 'E-post',
        password: 'Passord',
        loginButton: 'Logg Inn',
        loginFailed: 'Innlogging feilet',
        forgotPassword: 'Glemt passord?',
        registerLink: 'Registrer ny bruker',
        forgotTitle: 'Glemt passord',
        forgotSent: 'Hvis brukeren finnes, er det sendt en e-post med lenke for å sette nytt passord. Sjekk innboksen din.',
        forgotSend: 'Send lenke',
        backToLogin: 'Tilbake til innlogging',
        resetTitle: 'Sett nytt passord',
        resetInvalidTitle: 'Ugyldig lenke',
        resetInvalidBody: 'Lenken mangler eller er utløpt. Be om en ny.',
        newPassword: 'Nytt passord',
        repeatNewPassword: 'Gjenta nytt passord',
        resetButton: 'Endre passord',
        resetDone: 'Passordet er endret. Logg inn med det nye passordet.',
        resetFailedHint: '. Lenken kan være utløpt – be om en ny under «Glemt passord».',
        passwordMismatch: 'Passordene er ikke like',
        registerTitle: 'Registrer bruker',
        registerIntro: 'En bruker gir ingen tilgang i seg selv — et eksisterende medlem må legge deg til i organisasjonen etterpå.',
        name: 'Navn',
        repeatPassword: 'Gjenta passord',
        registerButton: 'Registrer',
        registerFailed: 'Registrering feilet',
        registerDone: 'Brukeren er opprettet',
        verifyEmail: 'Sjekk e-posten din og bekreft brukeren. Deretter kan du logge inn — og be et eksisterende medlem i organisasjonen din om å legge deg til under «Medlemmer».',
        hasAccount: 'Har du en bruker? Logg inn',
        genericError: 'Noe gikk galt',
        inviteJoined: (org: string) => org ? `Du er nå medlem av ${org}` : 'Du er nå medlem av organisasjonen',
        inviteAfterVerify: 'Åpne invitasjonslenken på nytt og logg inn etterpå, så blir du medlem av organisasjonen.',
    },
    validation: {
        required: 'Må fylles ut',
        invalidDate: 'Ugyldig dato',
        invalidNumber: 'Må være et tall',
        dropdownFallback: 'Skriv inn fritekst — det er ingen forhåndsdefinerte valg satt opp.',
    },
    admin: {
        nav: {
            oversikt: 'Oversikt',
            innhold: 'Innhold',
            pdfmal: 'PDF-mal',
            maler: 'Maler',
            medlemmer: 'Medlemmer',
            utstedte: 'Utstedte',
            publicForm: 'Se offentlig skjema ↗',
        },
    },
};

const en: Strings = {
    common: {
        cancel: 'Cancel',
        loading: 'Loading …',
    },
    landing: {
        tagline: 'Digitally verifiable certificates for volunteers – without storing personal data.',
        steps: [
            { title: '1. Fill in the form', text: 'The volunteer fills in the organization’s form with name, role and time period.' },
            { title: '2. The certificate is issued', text: 'The organization checks the content and generates a PDF with a QR code. The organization then deletes your submission – only a cryptographic hash remains.' },
            { title: '3. Anyone can verify', text: 'The QR code points to a verification page that confirms the certificate is genuine and unaltered.' },
        ],
        privacyTitle: 'Privacy is the whole point',
        privacyBody: 'Your submission is only stored until the organization has issued the certificate and deleted it. Of the certificate itself, no names, roles or dates are ever stored – only a cryptographic hash of the contents. If the database leaks, no issued certificates leak. Only the person holding the certificate (or its QR code) knows what was attested.',
        aboutLink: 'Read more about how attester.no works and what is stored',
        orgsTitle: 'Participating organizations',
        orgsSubtitle: 'Requesting a certificate? Go to your organization’s form:',
        adminLogin: 'Log in as administrator',
        contactPrompt: 'Want your organization to use attester.no?',
        contactLink: 'Get in touch on GitHub',
    },
    about: {
        metaTitle: 'How it works',
        title: 'How attester.no works',
        intro: 'attester.no proves a certificate is genuine – without permanently storing what it says. This page explains exactly what happens to your data.',
        flowTitle: 'What happens to your submission?',
        flowSteps: [
            'You fill in your organization’s form. The data is stored until the organization has reviewed it and issued the certificate.',
            'When the organization approves, the certificate is generated as a PDF with a QR code, and you receive it from the organization.',
            'After issuance the organization deletes your data from the database – only the cryptographic hash remains.',
            'If you don’t hear back, you can contact the organization at any time and ask them to delete your submission.',
        ],
        storedTitle: 'What is stored – and what is never stored?',
        storedIntro: 'Once the certificate is issued and the submission deleted, the database contains only:',
        storedItems: [
            'A cryptographic hash (a “fingerprint”) of the certificate’s contents',
            'Which organization issued it, and when',
            'Which PDF template was used',
            'A random ID that the QR code looks up',
        ],
        neverStoredIntro: 'This is NEVER stored as part of the certificate:',
        neverStoredItems: [
            'Your name',
            'Positions, roles or groups',
            'Dates and time periods',
            'Everything else written on the certificate',
        ],
        hashTitle: 'How can the certificate be verified if the contents aren’t stored?',
        hashBody: 'The QR code on the certificate carries the data – not the database. When someone scans the code, the verification page computes the fingerprint of the data in the code and compares it with the fingerprint we stored when the certificate was issued. If they match, the certificate is genuine and unaltered. Change as little as one character and they no longer match.',
        hashConsequence: 'The consequence: should the database leak, no personal data from issued certificates leaks. The server does not even know who the certificates are about. Only the person holding the paper certificate – or the QR code – can read the contents.',
        verifyTitle: 'How to verify a certificate',
        verifySteps: [
            'Scan the QR code on the certificate with your phone camera.',
            'The verification page opens and shows green if the certificate is genuine and unaltered, red if something is off.',
            'Compare the fields on the page with what is printed on paper.',
        ],
        contactTitle: 'Questions?',
        contactBody: 'Email hei@attester.no, or get in touch on GitHub.',
        backToFront: 'Back to the front page',
    },
    form: {
        title: (org: string) => `Request a certificate from ${org}`,
        intro: (org: string) => `Submit your information here to receive a certificate from ${org}!`,
        help: 'Help',
        adminLogin: 'Admin login',
        noTemplate: (id: string | null) => `No template found for this organization${id ? ` (id ${id})` : ''}.`,
        submit: 'Submit',
        confirmTitle: 'Confirm submission',
        confirmMessage: 'Are you sure you want to submit this data?',
        confirmButton: 'Yes, submit',
        submitError: 'Failed to save data: ',
        receivedTitle: 'Submission received',
        receivedWhatNext: 'What happens next:',
        receivedSteps: (org: string) => [
            `${org} reviews your information. Until that happens, your submission is stored with attester.no.`,
            `If approved, the certificate is generated as a PDF with a QR code, and you receive it from ${org}.`,
            `Once the certificate is issued, ${org} deletes your data from the database — only a cryptographic hash remains, so the certificate can be verified.`,
            `If you don’t hear back, you can contact ${org} and ask them to delete your submission.`,
        ],
        sendAnother: 'Submit another',
        helpTitle: 'What is this website?',
        helpBody: (org: string) => `This website issues certificates from ${org}. You submit your information, an administrator reviews it, and if approved you receive a PDF with a QR code — ${org} then deletes your information from the database. Only a hash is kept permanently, so the certificate can be verified.`,
        helpMore: 'Read more about how it works and what is stored',
        helpClose: 'Thanks! 😊',
    },
    verify: {
        title: 'Verification',
        checking: 'Checking the certificate …',
        validTitle: '✓ The certificate is valid',
        validBody: 'The details below match the certificate exactly as it was issued. Change as little as one character and it becomes invalid.',
        invalidTitle: '✗ The certificate is invalid',
        invalidBody: 'The details do not match any issued certificate. Either the link is incomplete (rescan the QR code), a field has been altered, or the certificate was never issued by this organization.',
        fieldsLabel: 'Attested details — you can edit a field to see verification fail:',
        aboutLink: 'How does this work?',
    },
    auth: {
        loginTitle: 'Log in',
        email: 'Email',
        password: 'Password',
        loginButton: 'Log in',
        loginFailed: 'Login failed',
        forgotPassword: 'Forgot password?',
        registerLink: 'Register a new account',
        forgotTitle: 'Forgot password',
        forgotSent: 'If the account exists, an email with a reset link has been sent. Check your inbox.',
        forgotSend: 'Send link',
        backToLogin: 'Back to login',
        resetTitle: 'Set a new password',
        resetInvalidTitle: 'Invalid link',
        resetInvalidBody: 'The link is missing or has expired. Request a new one.',
        newPassword: 'New password',
        repeatNewPassword: 'Repeat new password',
        resetButton: 'Change password',
        resetDone: 'Password changed. Log in with your new password.',
        resetFailedHint: '. The link may have expired – request a new one under “Forgot password”.',
        passwordMismatch: 'The passwords do not match',
        registerTitle: 'Register an account',
        registerIntro: 'An account grants no access by itself — an existing member must add you to the organization afterwards.',
        name: 'Name',
        repeatPassword: 'Repeat password',
        registerButton: 'Register',
        registerFailed: 'Registration failed',
        registerDone: 'Account created',
        verifyEmail: 'Check your email and confirm the account. Then log in — and ask an existing member of your organization to add you under “Members”.',
        hasAccount: 'Already have an account? Log in',
        genericError: 'Something went wrong',
        inviteJoined: (org: string) => org ? `You are now a member of ${org}` : 'You are now a member of the organization',
        inviteAfterVerify: 'Open the invite link again and log in afterwards to join the organization.',
    },
    validation: {
        required: 'Required',
        invalidDate: 'Invalid date',
        invalidNumber: 'Must be a number',
        dropdownFallback: 'Free text — no predefined options are set up.',
    },
    admin: {
        nav: {
            oversikt: 'Overview',
            innhold: 'Content',
            pdfmal: 'PDF template',
            maler: 'Templates',
            medlemmer: 'Members',
            utstedte: 'Issued',
            publicForm: 'View public form ↗',
        },
    },
};

export type Strings = typeof no;

export function getStrings(lang?: string | null): Strings {
    return lang === 'en' ? en : no;
}

export function normalizeLang(lang?: string | null): Lang {
    return lang === 'en' ? 'en' : 'no';
}
